# Generated by Django 3.1.2 on 2020-10-06 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ussd_call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=80, verbose_name='کد ارسالی')),
                ('mobile', models.CharField(max_length=15, verbose_name='شماره همراه')),
                ('session_id', models.CharField(max_length=50, verbose_name='شناسه نشست')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2020, 10, 6, 9, 14, 32, 314853), verbose_name='ژمان ارسال')),
            ],
        ),
    ]
