# Generated by Django 3.1.2 on 2020-10-06 08:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ussd_command_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نوع دستور')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ussd_call',
            options={'verbose_name': 'کدهای دریافتی USSD', 'verbose_name_plural': 'کدهای دریافتی USSD'},
        ),
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 12, 11, 28, 914605), verbose_name='ژمان ارسال'),
        ),
        migrations.CreateModel(
            name='ussd_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('command_id', models.IntegerField(verbose_name='ردیف دستور')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('command_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ussdapi.ussd_command_type')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussdapi.ussd_command', verbose_name='کد مادر')),
            ],
        ),
    ]
