# Generated by Django 3.1.2 on 2020-10-06 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0002_auto_20201006_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 12, 14, 21, 598119), verbose_name='ژمان ارسال'),
        ),
        migrations.AlterField(
            model_name='ussd_command',
            name='command_id',
            field=models.IntegerField(null=True, verbose_name='ردیف دستور'),
        ),
        migrations.AlterField(
            model_name='ussd_command',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ussdapi.ussd_command', verbose_name='کد مادر'),
        ),
    ]
