# Generated by Django 3.1.2 on 2020-10-06 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0004_auto_20201006_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 12, 30, 11, 764640), verbose_name='ژمان ارسال'),
        ),
        migrations.RemoveField(
            model_name='ussd_command',
            name='command_type',
        ),
        migrations.AddField(
            model_name='ussd_command',
            name='command_type',
            field=models.ManyToManyField(to='ussdapi.ussd_command_type'),
        ),
    ]
