# Generated by Django 3.1.2 on 2020-10-11 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0007_auto_20201011_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان کمپین')),
                ('short_title', models.CharField(max_length=30, verbose_name='عنوان کوتاه')),
                ('min_donation_amount', models.IntegerField(default=100000, verbose_name='حداقل مبلغ هر حمایت')),
            ],
            options={
                'verbose_name': 'کمپین ها',
                'verbose_name_plural': 'کمپین ها',
            },
        ),
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 15, 15, 28, 438908), verbose_name='ژمان ارسال'),
        ),
    ]
