# Generated by Django 3.1.2 on 2020-10-11 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0008_auto_20201011_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussd_command',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ussdapi.campaign'),
        ),
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 15, 24, 40, 523622), verbose_name='ژمان ارسال'),
        ),
    ]
