# Generated by Django 3.1.2 on 2020-10-11 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0009_auto_20201011_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 13, 21, 453543), verbose_name='ژمان ارسال'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 13, 21, 454541), verbose_name='تاریخ ایجاد')),
                ('payment_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('session_id', models.CharField(max_length=150, verbose_name='شناسه نشست')),
                ('mobile', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('amount', models.FloatField(verbose_name='مقدار حمایت')),
                ('bill_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='شناسه قبض')),
                ('bill_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='شناسه پرداخت')),
                ('card_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه بانک')),
                ('payment_gateway', models.CharField(blank=True, max_length=30, null=True, verbose_name='درگاه پرداخت')),
                ('campaing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ussdapi.campaign', verbose_name='کمپین')),
            ],
            options={
                'verbose_name': 'حمایت های مالی',
                'verbose_name_plural': 'حمایت های مالی',
            },
        ),
    ]
