# Generated by Django 3.1.2 on 2020-10-11 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0010_auto_20201011_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='unique_url_code',
            field=models.CharField(default='41B318', max_length=6, verbose_name='شناسه یکتای اینترنتی'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 55, 42, 694549), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 55, 42, 693552), verbose_name='ژمان ارسال'),
        ),
    ]
