# Generated by Django 3.1.2 on 2020-10-13 05:16

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0011_auto_20201011_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='مقدار حمایت'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 10, 13, 8, 46, 11, 403680), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='unique_url_code',
            field=models.CharField(default='A41C7B', max_length=6, verbose_name='شناسه یکتای اینترنتی'),
        ),
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 10, 13, 8, 46, 11, 402683), verbose_name='ژمان ارسال'),
        ),
    ]
