# Generated by Django 3.1.2 on 2020-10-13 07:01

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0012_auto_20201013_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='sms_inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20, verbose_name='شناسه پیام')),
                ('sender', models.CharField(max_length=30, verbose_name='شماره درگاه')),
                ('receptor', models.CharField(max_length=15, verbose_name='شماره مخاطب')),
                ('date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ ارسال')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.IntegerField(verbose_name='کد وضعیت')),
                ('status_text', models.CharField(max_length=20, verbose_name='متن وضعیت')),
                ('cost', models.FloatField(verbose_name='هزینه پیامک')),
            ],
            options={
                'verbose_name': 'لیست پیامک های ارسالی',
                'verbose_name_plural': 'لیست پیامک های ارسالی',
            },
        ),
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 10, 13, 10, 31, 27, 119854), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='unique_url_code',
            field=models.CharField(default='3037D6', max_length=6, verbose_name='شناسه یکتای اینترنتی'),
        ),
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 10, 13, 10, 31, 27, 117858), verbose_name='ژمان ارسال'),
        ),
    ]
