# Generated by Django 3.1.2 on 2020-10-13 11:15

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ussdapi', '0013_auto_20201013_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creation_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 10, 13, 14, 45, 49, 265760), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='unique_url_code',
            field=models.CharField(default='46753D', max_length=6, unique=True, verbose_name='شناسه یکتای اینترنتی'),
        ),
        migrations.AlterField(
            model_name='ussd_call',
            name='date_time',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 10, 13, 14, 45, 49, 263762), verbose_name='ژمان ارسال'),
        ),
    ]
